// config-schema.json -> types/settings-keys.d.ts (the SlicerSettings interface, 907 keys).
// Regenerate: node types/gen_settings_types.mjs      (do not hand-edit — fix this script instead)
//
// ponytail: mapping is driven purely by the schema's coXxx type. min/max and nullable are not reflected in types
//   (they are runtime validation, not type validation, and 907 keys x branded number slows tsc down).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const schema = JSON.parse(readFileSync(resolve(here, '../data/config-schema.json'), 'utf8'))

const lit = (v) => "'" + String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'"
// Some coEnum entries have no enum_values (70/64 mismatch) -> fail open to string.
const enumOf = (o) => (Array.isArray(o.enum_values) && o.enum_values.length)
  ? o.enum_values.map(lit).join(' | ')
  : 'string'

// Vector types are `T[] | T` — settingScalar() accepts both, and the UI edits only the first element (settings.js:9).
const vec = (t) => `${/\|/.test(t) ? `(${t})` : t}[] | ${/\|/.test(t) ? `(${t})` : t}`

function tsType(o) {
  switch (o.type) {
    case 'coBool': return 'boolean'
    case 'coBools': return vec('boolean')
    case 'coInt': case 'coFloat': case 'coPercent': return 'number'
    case 'coInts': case 'coFloats': case 'coPercents': return vec('number')
    case 'coFloatOrPercent': return 'number | string'
    case 'coFloatsOrPercents': return vec('number | string')
    case 'coString': return 'string'
    case 'coStrings': return vec('string')
    case 'coEnum': return enumOf(o)
    case 'coEnums': return vec(enumOf(o))
    case 'coPoint': return 'Point'
    case 'coPoints': return 'Point[]'
    case 'coPointsGroups': return 'Point[][]'
    default: return 'unknown'
  }
}

const esc = (s) => String(s).replace(/\*\//g, '*\\/')
const ident = (k) => /^[A-Za-z_$][\w$]*$/.test(k) ? k : lit(k).replace(/^'|'$/g, (m) => m === "'" ? "'" : m)

const lines = []
for (const key of Object.keys(schema).sort()) {
  const o = schema[key]
  const doc = [o.label, o.sidetext ? `(${o.sidetext})` : '', o.tooltip].filter(Boolean).join(' — ')
  if (doc) lines.push(`  /** ${esc(doc).replace(/\s*\n\s*/g, ' ')} */`)
  const name = /^[A-Za-z_$][\w$]*$/.test(key) ? key : lit(key)
  lines.push(`  ${name}?: ${tsType(o)}`)
}

writeFileSync(resolve(here, 'settings-keys.d.ts'), `// AUTO-GENERATED by types/gen_settings_types.mjs — DO NOT EDIT.
// Source: data/config-schema.json (${Object.keys(schema).length} keys)

 /** [x, y] — coPoint family */
export type Point = [number, number]

/**
  * Slicer settings map. Sparse — it holds only edited keys; missing keys use the config-schema default.
  * If you need arbitrary key extension, widen it with \`SlicerSettings & Record<string, unknown>\`.
 */
export interface SlicerSettings {
${lines.join('\n')}
}

 /** Setting keys that exist in config-schema */
export type SettingKey = keyof SlicerSettings & string
`)
console.log(`settings-keys.d.ts written — ${Object.keys(schema).length} keys`)
