// config-schema.json → types/settings-keys.d.ts (SlicerSettings 인터페이스, 907키).
// 재생성: node types/gen_settings_types.mjs      (수동 편집 금지 — 이 스크립트만 고칠 것)
//
// ponytail: 스키마의 coXxx 타입만 보고 매핑한다. min/max·nullable 은 타입에 반영하지 않음
//   (런타임 검증이지 타입 검증이 아니고, 907키 × branded number 는 tsc 를 느리게 만든다).
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const schema = JSON.parse(readFileSync(resolve(here, '../data/config-schema.json'), 'utf8'))

const lit = (v) => "'" + String(v).replace(/\\/g, '\\\\').replace(/'/g, "\\'") + "'"
// enum_values 가 없는 coEnum 도 있다(70/64 불일치) → string 으로 fail-open.
const enumOf = (o) => (Array.isArray(o.enum_values) && o.enum_values.length)
  ? o.enum_values.map(lit).join(' | ')
  : 'string'

// 벡터형은 `T[] | T` — settingScalar() 가 둘 다 받고, UI 는 첫 원소만 편집한다(settings.js:9).
const vec = (t) => `${/\|/.test(t) ? `(${t})` : t}[] | ${/\|/.test(t) ? `(${t})` : t}`

function tsType(o) {
  switch (o.type) {
    case 'coBool': return 'boolean'
    case 'coBools': return vec('boolean')
    case 'coInt': case 'coFloat': case 'coPercent': return 'number'
    case 'coInts': case 'coFloats': case 'coPercents': return vec('number')
    case 'coFloatOrPercent': return 'number | string'
    case 'coFloatsOrPercents': return vec('number | string')
    case 'coString': return 'string'
    case 'coStrings': return vec('string')
    case 'coEnum': return enumOf(o)
    case 'coEnums': return vec(enumOf(o))
    case 'coPoint': return 'Point'
    case 'coPoints': return 'Point[]'
    case 'coPointsGroups': return 'Point[][]'
    default: return 'unknown'
  }
}

const esc = (s) => String(s).replace(/\*\//g, '*\\/')
const ident = (k) => /^[A-Za-z_$][\w$]*$/.test(k) ? k : lit(k).replace(/^'|'$/g, (m) => m === "'" ? "'" : m)

const lines = []
for (const key of Object.keys(schema).sort()) {
  const o = schema[key]
  const doc = [o.label, o.sidetext ? `(${o.sidetext})` : '', o.tooltip].filter(Boolean).join(' — ')
  if (doc) lines.push(`  /** ${esc(doc).replace(/\s*\n\s*/g, ' ')} */`)
  const name = /^[A-Za-z_$][\w$]*$/.test(key) ? key : lit(key)
  lines.push(`  ${name}?: ${tsType(o)}`)
}

writeFileSync(resolve(here, 'settings-keys.d.ts'), `// AUTO-GENERATED by types/gen_settings_types.mjs — DO NOT EDIT.
// Source: data/config-schema.json (${Object.keys(schema).length} keys)

/** [x, y] — coPoint 계열 */
export type Point = [number, number]

/**
 * 슬라이서 설정 맵. sparse — 편집한 키만 담고, 없는 키는 config-schema 의 default 가 쓰인다.
 * 임의 키 확장이 필요하면 \`SlicerSettings & Record<string, unknown>\` 로 넓혀서 쓸 것.
 */
export interface SlicerSettings {
${lines.join('\n')}
}

/** config-schema 에 존재하는 설정 키 */
export type SettingKey = keyof SlicerSettings & string
`)
console.log(`settings-keys.d.ts written — ${Object.keys(schema).length} keys`)
