#!/usr/bin/env node
// Generates the kernel-parameter reference table in engine/README.md.
//
// Why generated: `slice()` takes a flat params object and that object WAS documented as "see src/settings.js for
// the full shape" — a pointer at source code. It is also bigger than the settings map can reach: the kernel reads
// 159 keys, deriveKernelParams emits 93 from an empty settings map, so a third of the contract had no path to a
// consumer at all. A hand-written table would drift the same way the AGENTS.md key counts already did (89 -> 93).
//
// Three inputs, each the authority for one column:
//   · wasm-core/params.cpp  — WHICH keys exist. Every read is `p.<field> = j<reader>(j,"<key>", …)`, so the reader
//                             call sites are the definition of the accepted key set. Nothing else can be.
//   · wasm-core/params.h    — the C++ type, the default, and the trailing `//` comment as the description.
//   · engine/src/settings.js — which schema key produces which kernel param, discovered by PROBING
//                             deriveKernelParams rather than by parsing it (see probeSchemaMapping below).
//
// Usage:
//   node types/gen_kernel_params.mjs           # rewrite the table in engine/README.md
//   node types/gen_kernel_params.mjs --check   # exit 1 if the file is stale (build/CI gate)
import { readFileSync, writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { schema } from '../engine/src/data.js'
import { deriveKernelParams } from '../engine/src/settings.js'

const here = dirname(fileURLToPath(import.meta.url))
const CORE = join(here, '..', 'wasm-core')
const README = join(here, '..', 'engine', 'README.md')
const BEGIN = '<!-- KERNEL-PARAMS:BEGIN — generated by types/gen_kernel_params.mjs, do not edit by hand -->'
const END = '<!-- KERNEL-PARAMS:END -->'

// ---- 1. the accepted key set, from the reader call sites --------------------------------------------------
// A line can carry more than one key: the tree-support shape options are read as
// `jget(j,"…_organic", jget(j,"…", p.field))`, i.e. the organic-suffixed name wins and the suffix-less one is its
// fallback. Both are accepted, both land in the same field, so both belong in the table — with the first one
// marked as the alias it is.
function readerKeys() {
  const source = readFileSync(join(CORE, 'params.cpp'), 'utf8')
  const rows = []
  for (const line of source.split('\n')) {
    const assigned = line.match(/^\s*p\.([a-z0-9_]+)\s*=/)
    if (!assigned) continue
    const keys = [...line.matchAll(/\bj[a-z_]+\(j,\s*"([a-z0-9_]+)"/g)].map(m => m[1])
    if (!keys.length) continue
    const reader = line.match(/\b(j[a-z_]+)\(j,/)?.[1] ?? 'jget'
    keys.forEach((key, i) => rows.push({ key, field: assigned[1], reader, aliasOf: i > 0 ? keys[0] : null }))
  }
  return rows
}

// ---- 2. type, default and description, from the struct ----------------------------------------------------
// Only the TRAILING `//` comment is taken as the description. Several fields carry a paragraph of design
// rationale above them instead (wipe_tower_real has ten lines on why it defaults off), and the last line of such
// a block reads as a description while being the opposite — a caveat about something else. A blank description
// is honest; a wrong one is not.
// ponytail: no multi-line comment reconstruction. Add it when a field's trailing comment is actually missing AND
//   the description matters more than the key/type/default the row already carries.
function structFields() {
  const source = readFileSync(join(CORE, 'params.h'), 'utf8')
  const out = {}
  for (const raw of source.split('\n')) {
    const line = raw.trim()
    if (!line.startsWith('double') && !line.startsWith('int') && !line.startsWith('bool') &&
        !line.startsWith('std::string') && !line.startsWith('std::vector')) continue
    const split = line.indexOf('//')
    const code = (split < 0 ? line : line.slice(0, split)).trim().replace(/;$/, '').trim()
    const note = split < 0 ? '' : line.slice(split + 2).trim()
    const type = code.match(/^(std::vector<[a-z:]+>|std::string|double|int|bool)\s+/)?.[1]
    if (!type) continue
    // `double a=1, b=2, c` — one type, several fields, at most one trailing comment shared by all of them.
    for (const decl of code.slice(type.length).split(',')) {
      const name = decl.trim().match(/^([a-z0-9_]+)/)?.[1]
      if (!name) continue
      const value = decl.includes('=') ? decl.slice(decl.indexOf('=') + 1).trim() : ''
      out[name] = { type: type.replace('std::', ''), default: value, note }
    }
  }
  return out
}

// ---- 3. schema key -> kernel param, by probing ------------------------------------------------------------
// Derived from BEHAVIOUR, not from reading settings.js. The mapping there is not a table: a param can come from a
// renamed key (initial_layer_print_height -> first_layer_height), a rescale (sparse_infill_density 15 -> 0.15), a
// bbox over a point list (printable_area -> bed_width/bed_depth) or an array whose second entry is what makes the
// param appear at all (nozzle_temperature[] -> extruder_nozzle_temp). A regex over the source would have to
// re-implement each of those; setting one key and seeing which params move cannot be wrong about any of them.
const PROBE_BY_TYPE = {
  coBool: [true, false], coBools: [[true, true], [false, false]],
  coFloat: [7.25], coFloats: [[7.25, 8.5]],
  coInt: [7], coInts: [[7, 8]],
  coPercent: [77], coPercents: [[77, 88]],
  coFloatOrPercent: [7.25, '77%'], coFloatsOrPercents: [[7.25, 8.5], ['77%', '88%']],
  coString: ['probe'], coStrings: [['probe', 'probe2']],
  coPoint: [[7, 8]], coPoints: [[[0, 0], [123, 0], [123, 77], [0, 77]]],
  coPointsGroups: [[[7, 8], [9, 10]]],
}
const probesFor = (key) => {
  const option = schema[key]
  if (option?.enum_values?.length) {
    const values = option.enum_values.filter(v => v !== option.default)
    return option.type === 'coEnums' ? [values] : values
  }
  return PROBE_BY_TYPE[option?.type] ?? ['probe']
}

function probeSchemaMapping() {
  const base = deriveKernelParams({})
  const sources = {}          // kernel param -> Set of schema keys that move it
  const same = (a, b) => JSON.stringify(a ?? null) === JSON.stringify(b ?? null)
  for (const schemaKey of Object.keys(schema)) {
    for (const probe of probesFor(schemaKey)) {
      let derived
      try { derived = deriveKernelParams({ [schemaKey]: probe }) } catch { continue }
      for (const param of new Set([...Object.keys(base), ...Object.keys(derived)]))
        if (!same(base[param], derived[param])) (sources[param] ??= new Set()).add(schemaKey)
    }
  }
  return sources
}

// ---- 4. the table -----------------------------------------------------------------------------------------
// Grouped by the same buckets the doc review used, because "which of these can I reach from the settings map"
// is the question a consumer actually arrives with, and the answer is almost perfectly predicted by the group.
const GROUPS = [
  ['Geometry and walls', k => /^(layer_height|first_layer_height|line_width|wall_loops|.*line_width|spiral_mode|wall_generator|gcode_resolution|auto_center)$/.test(k)],
  ['Infill', k => /^(infill_|sparse_infill_|top_shell|bottom_shell|ironing_)/.test(k)],
  ['Speeds, flow and temperature', k => /^(print_speed|first_layer_speed|travel_speed|bridge_speed|nozzle_|bed_temp|filament_diameter|flow_ratio|fan_speed|close_fan|full_fan|slow_down|pressure_advance|enable_pressure_advance|max_volumetric|machine_(accel|jerk|max)_)/.test(k)],
  ['Retraction and seams', k => /^(retract|z_hop|seam_|scarf_length)/.test(k)],
  ['Adhesion (skirt, brim, raft)', k => /^(skirt_|brim_|raft_)/.test(k)],
  ['Support', k => /^(enable_support|support_|bridge_no_support|tree_)/.test(k)],
  ['Multi-material and prime tower', k => /^(extruder_|mm_group|filament_(map|type|settings_id|density|cost)|flush_|prime_|enable_prime_tower|wipe_tower_real|.*_filament_id)$/.test(k)],
  ['Bed and machine G-code', k => /^(bed_|printable_height|machine_start_gcode|machine_end_gcode|enable_arc_fitting)/.test(k)],
  ['Engine, streaming and diagnostics', () => true],
]

const escape = (text) => String(text).replace(/\|/g, '\\|')
const TYPE_LABEL = { 'vector<double>': '`number[]`', 'vector<string>': '`string[]`', string: '`string`', double: '`number`', int: '`number`', bool: '`boolean`' }

function buildTable() {
  const rows = readerKeys()
  const fields = structFields()
  const sources = probeSchemaMapping()
  const seen = new Set()
  const grouped = new Map(GROUPS.map(([name]) => [name, []]))

  for (const row of rows) {
    if (seen.has(row.key)) continue
    seen.add(row.key)
    const field = fields[row.field] ?? {}
    const from = [...(sources[row.key] ?? [])].sort()
    const group = GROUPS.find(([, match]) => match(row.key))[0]
    grouped.get(group).push({
      key: row.key,
      type: TYPE_LABEL[field.type] ?? `\`${field.type ?? '?'}\``,
      default: field.default ? `\`${escape(field.default.replace(/"/g, "'"))}\`` : (row.reader.includes('arr') ? '`[]`' : '—'),
      from: from.length ? from.map(k => `\`${k}\``).join(', ') : '—',
      note: escape(row.aliasOf ? `fallback spelling — \`${row.aliasOf}\` wins when both are sent` : field.note),
    })
  }

  const derivable = new Set(Object.keys(sources))
  const reachable = rows.filter(r => derivable.has(r.key)).length
  const lines = [
    BEGIN,
    '',
    `The kernel accepts **${seen.size} parameters**. \`deriveKernelParams()\` produces ${reachable} of them from the`,
    `OrcaSlicer settings map; the remaining ${seen.size - reachable} have no schema key behind them and can only be set by writing`,
    'the params object directly — those rows show `—` in the *From setting* column.',
    '',
    'A parameter left out of the object keeps the default listed here, so sending a partial object is normal and is',
    'what `deriveKernelParams()` itself does.',
    '',
    '*From setting* names the schema key the value is read from, which is often **not** the same name and not the',
    'same unit — `first_layer_height` comes from `initial_layer_print_height`, and `infill_density` is',
    '`sparse_infill_density` divided by 100 (a settings map holding `20` produces `0.2` here).',
    '',
  ]
  for (const [name, entries] of grouped) {
    if (!entries.length) continue
    lines.push(`### ${name}`, '', '| Kernel param | Type | Default | From setting | Notes |', '| --- | --- | --- | --- | --- |')
    for (const e of entries.sort((a, b) => a.key.localeCompare(b.key)))
      lines.push(`| \`${e.key}\` | ${e.type} | ${e.default} | ${e.from} | ${e.note} |`)
    lines.push('')
  }
  lines.push(END)
  return lines.join('\n')
}

const table = buildTable()
const readme = readFileSync(README, 'utf8')
const start = readme.indexOf(BEGIN)
const stop = readme.indexOf(END)
if (start < 0 || stop < 0) {
  console.error(`gen_kernel_params: markers not found in ${README}. Add:\n${BEGIN}\n${END}`)
  process.exit(1)
}
const next = readme.slice(0, start) + table + readme.slice(stop + END.length)

if (process.argv.includes('--check')) {
  if (next !== readme) {
    console.error('gen_kernel_params: engine/README.md is stale — run `node types/gen_kernel_params.mjs`')
    process.exit(1)
  }
  console.log(`gen_kernel_params: engine/README.md is current (${table.split('\n').filter(l => l.startsWith('| `')).length} params)`)
} else {
  writeFileSync(README, next)
  console.log(`gen_kernel_params: wrote ${table.split('\n').filter(l => l.startsWith('| `')).length} params into engine/README.md`)
}
